---
- name: "Pull Jellyfin image"
  containers.podman.podman_image:
    name: "{{ container.image }}"

- name: Creates Jellyfin cache directory
  file:
    path: "{{ host.volumes.cache }}"
    state: "directory"

- name: Creates Jellyfin config directory
  file:
    path: "{{ host.volumes.config }}"
    state: "directory"

- name: Creates Jellyfin media directory
  file:
    path: "{{ ssd_external_mount_point }}"
    state: "directory"

- name: Mount external SSD
  ansible.posix.mount:
    path: "{{ ssd_external_mount_point }}"
    src: LABEL=External
    fstype: ext4
    state: present

- name: Mount and bind a volume
  ansible.posix.mount:
    path: "{{ ssd_external_mount_point }}"
    src: LABEL=External
    opts: defaults,nofail
    state: mounted
    fstype: ext4    

- name: Allow Jellyfin to listen on tcp port 8096
  community.general.seport:
    ports: "{{ network.ports.main.port }}"
    proto: "{{ network.ports.main.proto }}"
    setype: "http_port_t"
    state: "present"

- name: "Start Jellyfin"
  containers.podman.podman_container:
    name: "{{ container.name }}"
    image: "{{ container.image }}"
    state: "started"
    recreate: true
    env:
      "TZ": "{{ timezone }}"
    expose:
      - "{{ network.ports.main.expose }}"
    ports:
      - "{{ network.ports.main.bind }}"
    volumes:
      - "{{ host.volumes.config }}:{{ container.volumes.config }}:Z"
      - "{{ host.volumes.cache }}:{{ container.volumes.cache }}:Z"
      - "{{ host.volumes.media }}:{{ container.volumes.media }}:Z"
    restart_policy: always
