---
- name: "Pull Jellyfin image"
  containers.podman.podman_image:
    name: "{{ image.name }}"
    
- name: Creates Jellyfin cache directory
  file:
    path: "{{ cache.dir }}"
    state: "directory"
    
- name: Creates Jellyfin config directory
  file:
    path: "{{ config.dir }}"
    state: "directory"

- name: Allow Jellyfin to listen on tcp port 8096
  community.general.seport:
    ports: "8096"
    proto: "tcp"
    setype: "http_port_t"
    state: "present"
    
- name: Mount external SSD
  ansible.posix.mount:
    path: /home/{{ username }}/MEDIA
    src: LABEL=MEDIA
    fstype: fat32
    state: present
  
- name: "Start Jellyfin"
  containers.podman.podman_container:
    name: "{{ container.name }}"
    image: "{{ image.name }}"
    state: "started"
    env:
      "TZ": "{{ timezone }}"
    expose:
      - "8096/tcp"
    ports:
      - "8096:8096/tcp"
    
    volumes:
      - "{{ config.dir }}:{{ container.config.dir }}:Z"
      - "{{ cache.dir }}:{{ container.cache.dir }}:Z"
      - "/home/{{ username }}/MEDIA/Media:/media:Z"
    restart_policy: always