---
- name: "Pull Jellyfin image"
  containers.podman.podman_image:
    name: "{{ container.image }}"

- name: Creates Jellyfin cache directory
  file:
    path: "{{ volumes.cache }}"
    state: "directory"

- name: Creates Jellyfin config directory
  file:
    path: "{{ volumes.config }}"
    state: "directory"

- name: Creates Jellyfin media directory
  file:
    path: "{{ ssd_external_mount_point }}"
    state: "directory"

- name: Mount external SSD
  ansible.posix.mount:
    path: "{{ ssd_external_mount_point }}"
    src: LABEL=External
    fstype: ext4
    state: present

- name: Mount and bind a volume
  ansible.posix.mount:
    path: "{{ ssd_external_mount_point }}"
    src: LABEL=External
    opts: defaults,nofail
    state: mounted
    fstype: ext4    

- name: Allow Jellyfin to listen on tcp port 8096
  community.general.seport:
    ports: "8096"
    proto: "tcp"
    setype: "http_port_t"
    state: "present"

- name: "Start Jellyfin"
  containers.podman.podman_container:
    name: "{{ container.name }}"
    image: "{{ container.image }}"
    state: "started"
    env:
      "TZ": "{{ timezone }}"
    expose:
      - "8096/tcp"
    ports:
      - "8096:8096/tcp"
    volumes:
      - "{{ volumes.config }}:{{ container.volumes.config }}:Z"
      - "{{ volumes.cache }}:{{ container.volumes.cache }}:Z"
      - "{{ volumes.media }}:{{ container.volumes.media }}:Z"
    restart_policy: always
