- name: "Configure Homeserver"
  hosts: "all"
  
  vars_files:
    - "vars/main.yml"
    - "vars/vault.yml"

  roles:
    - role: system
      tags: system
    - role: adguard
      tags:
        - adguard
        - container
    - role: jellyfin
      tags:
        - jellyfin
        - container
    - role: homebridge
      tags:
        - homebridge
        - container
    - role: git
      tags:
        - git
        - container
    - role: pocketbase
      tags:
        - pocketbase
        - container
    - role: mqtt
      tags:
        - mqtt
        - container
