---
- name: Set the name of a sudo group
  set_fact:
    sudo_group: wheel
   
- name: Create a login user
  user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}" 
    groups: 
      - "{{ sudo_group }}"
      - users
    state: present
    append: true

- name: Ensure group "{{ username }}" exists
  group:
    name: "{{ username }}"
    state: present
    
- name: Chmod the user home directory
  file:
    path: "/home/{{ username }}"
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: yes
    
- name: Allow 'sudo' group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%{{ sudo_group }}'
    line: '%{{ sudo_group }} ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Copy the public SSH key 
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ ssh_public_key }}"