---
container:
  name: "jellyfin"
  image: "ghcr.io/linuxserver/jellyfin:latest"
  volumes:
    config: "/config"
    cache: "/cache"
    media: "/media"
volumes:
  config: "/home/{{ username }}/jellyfin/config"
  cache: "/home/{{ username }}/jellyfin/cache"
  media: "/home/{{ username }}/External/Media"
