---
container:
  name: "jellyfin"
  image: "ghcr.io/linuxserver/jellyfin:latest"
  volumes:
    config: "/config"
    cache: "/cache"
    media: "/media"
host:
  volumes:
    config: "/home/{{ username }}/External/jellyfin/config"
    cache: "/home/{{ username }}/External/jellyfin/cache"
    media: "/home/{{ username }}/External/Media"
network:
  ports:
    main:
      port: 8096
      proto: "tcp"
      expose: "8096/tcp"
      bind: "8096:8096/tcp"
