---
- name: "Pull EMQX image"
  containers.podman.podman_image:
    name: "{{ containers.mqtt.image }}"

# - name: "Pull Proxy image"
#   containers.podman.podman_image:
#     name: "{{ containers.proxy.image }}"   

- name: Modify SELinux to allow necessary ports for Homebridge
  community.general.seport:
    ports: "{{ item.value.port }}"
    proto: "{{ item.value.proto }}"
    setype: "http_port_t"
    state: "present"
  loop: "{{ network.ports|dict2items }}"

- name: "Start EMQX"
  containers.podman.podman_container:
    name: "{{ containers.mqtt.name }}"
    image: "{{ containers.mqtt.image }}"
    state: "started"
    recreate: true
    env:
      "TZ": "{{ timezone }}"
    expose:
      - "{{ network.ports.mqtt_tcp.expose }}"
      - "{{ network.ports.mqtt_ssl_tcp.expose }}"
      - "{{ network.ports.websocket_tcp.expose }}"
      - "{{ network.ports.websocket_ssl_tcp.expose }}"
      - "{{ network.ports.webui.expose }}"
    ports:
      - "{{ network.ports.mqtt_tcp.bind }}"
      - "{{ network.ports.mqtt_ssl_tcp.bind }}"
      - "{{ network.ports.websocket_tcp.bind }}"
      - "{{ network.ports.websocket_ssl_tcp.bind }}"
      - "{{ network.ports.webui.bind }}"
    restart_policy: always

# - name: "Start Proxy"
#   containers.podman.podman_container:
#     name: "{{ containers.proxy.name }}"
#     image: "{{ containers.proxy.image }}"
#     state: "started"
#     env:
#       "TZ": "{{ timezone }}"
#     expose:
#       - "{{ network.ports.proxy.expose }}"
#     ports:
#       - "{{ network.ports.proxy.bind }}"
#     restart_policy: always
