---
- name: "Pull EMQX image"
  containers.podman.podman_image:
    name: "{{ mqtt.container.image }}"

- name: "Pull Proxy image"
  containers.podman.podman_image:
    name: "{{ proxy.container.image }}"   

- name: Allow EMQX to listen on tcp port 8096
  community.general.seport:
    ports: "1883"
    proto: "tcp"
    setype: "http_port_t"
    state: "present"
    
- name: Allow EMQX to listen on tcp port 8096
  community.general.seport:
    ports: "8083"
    proto: "tcp"
    setype: "http_port_t"
    state: "present"

- name: Allow EMQX to listen on tcp port 8096
  community.general.seport:
    ports: "8084"
    proto: "tcp"
    setype: "http_port_t"
    state: "present"
    
- name: Allow EMQX to listen on tcp port 8096
  community.general.seport:
    ports: "8883"
    proto: "tcp"
    setype: "http_port_t"
    state: "present"

- name: Allow EMQX to listen on tcp port 8096
  community.general.seport:
    ports: "18083"
    proto: "tcp"
    setype: "http_port_t"
    state: "present"

- name: "Start EMQX"
  containers.podman.podman_container:
    name: "{{ mqtt.container.name }}"
    image: "{{ mqtt.container.image }}"
    state: "started"
    env:
      "TZ": "{{ timezone }}"
    expose:
      - "1883/tcp"
      - "8083/tcp"
      - "8084/tcp"
      - "8883/tcp"
      - "18083/tcp"
    ports:
      - "1883:1883/tcp"
      - "8083:8083/tcp"
      - "8084:8084/tcp"
      - "8883:8883/tcp"
      - "18083:18083/tcp"
    restart_policy: always

- name: Allow the proxy to listen on tcp port 8080
  community.general.seport:
    ports: "8080"
    proto: "tcp"
    setype: "http_port_t"
    state: "present"

- name: "Start Proxy"
  containers.podman.podman_container:
    name: "{{ proxy.container.name }}"
    image: "{{ proxy.container.image }}"
    state: "started"
    env:
      "TZ": "{{ timezone }}"
    expose:
      - "8080/tcp"
    ports:
      - "8080:8080/tcp"
    restart_policy: always
