---
container:
  name: "adguardhome"
  conf:
    dir: "/opt/adguardhome/conf"
  work:
    dir: "/opt/adguardhome/work"
image:
  name: "docker.io/adguard/adguardhome:latest"
conf:
  dir: "/home/{{ username }}/adguardhome/conf"
work:
  dir: "/home/{{ username }}/adguardhome/work"