---
container:
  name: "adguardhome"
  image: "docker.io/adguard/adguardhome:latest"
  volumes:
    conf: "/opt/adguardhome/conf"
    work: "/opt/adguardhome/work"
volumes:
  conf: "/home/{{ username }}/adguardhome/conf"
  work: "/home/{{ username }}/adguardhome/work"