---
- name: "Pull Homebridge image"
  containers.podman.podman_image:
    name: "{{ container.image }}"
  
- name: Creates Homebridge directory
  file:
    path: "{{ host.volumes.homebridge }}"
    state: "directory"

- name: Modify SELinux to allow necessary ports for Homebridge
  community.general.seport:
    ports: "{{ item.value.port }}"
    proto: "{{ item.value.proto }}"
    setype: "http_port_t"
    state: "present"
  loop: "{{ network.ports|dict2items }}"
    
- name: "Start Homebridge"
  containers.podman.podman_container:
    name: "{{ container.name }}"
    image: "{{ container.image }}"
    state: "started"
    env:
      "TZ": "{{ timezone }}"
    expose:
      - "{{ network.ports.homekit_tcp.expose }}"
      - "{{ network.ports.homekit_udp.expose }}"
      - "{{ network.ports.webui.expose }}"
    ports:
      - "{{ network.ports.homekit_tcp.bind }}"
      - "{{ network.ports.homekit_udp.bind }}"
      - "{{ network.ports.webui.bind }}"
    volumes:
      - "{{ host.volumes.homebridge }}:{{ container.volumes.homebridge }}:Z"
    restart_policy: always
