---
- name: Creates SSD Mount Point
  file:
    path: "{{ ssd_external_mount_point }}"
    state: "directory"

- name: Mount external SSD
  ansible.posix.mount:
    path: "{{ ssd_external_mount_point }}"
    src: LABEL=External
    fstype: ext4
    state: present

- name: Creates directory to store database
  file:
    path: "{{ host.volumes.data }}"
    state: "directory"
    recurse: true
    
- name: Creates directory to store build artifacts
  file:
    path: "/tmp/podman/{{ container.name }}"
    state: "directory"
    recurse: true
    
- name: Copy Dockerfile
  ansible.builtin.template:
    src: "Dockerfile.j2"
    dest: "/tmp/podman/{{ container.name }}/Dockerfile"

- name: "Allow pocketbase to listen on tcp port {{ network.ports.main.expose }}"
  community.general.seport:
    ports: "{{ network.ports.main.port }}"
    proto: "tcp"
    setype: "http_port_t"
    state: "present"

- name: Build Pocketbase image
  containers.podman.podman_image:
    name: "{{ container.name }}"
    path: "/tmp/podman/{{ container.name }}"
    force: true

- name: "Start Pocketbase"
  containers.podman.podman_container:
    name: "{{ container.name }}"
    image: pocketbase:latest
    recreate: true
    state: "started"
    expose:
      - "{{ network.ports.main.expose }}"
    ports:
      - "{{ network.ports.main.bind }}"
    volumes:
      - "{{ host.volumes.data }}:{{ container.volumes.data }}:Z"
    restart_policy: always